name: orgtrack
description: OrgTrack - Aplikasi Pemantauan Kegiatan Organisasi Kampus
publish_to: "none"

version: 1.0.0+1

# =========================
# WAJIB: SDK CONSTRAINT
# =========================
environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ===== CORE =====
  get: ^4.6.6
  cupertino_icons: ^1.0.8

  # ===== FIREBASE (MODUL 6) =====
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.0

  # ===== STORAGE & DB =====
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ===== UI & UTIL =====
  intl: ^0.20.2
  image_picker: ^1.1.1
  fl_chart: ^1.1.1
  animate_do: ^4.2.0
  google_fonts: ^6.3.2
  lottie: ^2.7.0
  iconsax: ^0.0.8

  # ===== QR / BARCODE =====
  barcode_widget: ^2.0.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3

  # ===== NETWORK =====
  dio: ^5.9.0
  http: ^1.5.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
